"""
Market AI — Hermes Agent Skills & Capabilities Registry
Maintains detailed registry of all 12 autonomous skills and quantitative reasoning modules operated by Hermes.
"""

from typing import List, Dict, Any


HERMES_SKILLS_REGISTRY: List[Dict[str, Any]] = [
    {
        "skill_id": "SKILL_TECHNICAL_CHART_ANALYSIS",
        "name": "Technical Chart Analysis & Indicators",
        "category": "QUANT_ANALYSIS",
        "status": "ACTIVE",
        "version": "v2.1.0",
        "description": "Calculates 20/50/200 DMAs, RSI-14 momentum divergence, MACD crossovers, ATR volatility bands, and Bollinger breakouts on NSE/BSE candlestick data.",
        "input_schema": {"symbol": "str", "candles": "List[Candle]", "timeframe": "str"},
        "output_schema": {"rsi_14": "float", "trend": "str", "key_levels": "Dict"},
        "latency_ms": 12,
        "tools_used": ["FeaturePipeline", "FeatureCalculator", "YahooFinanceMarketDataProvider"],
    },
    {
        "skill_id": "SKILL_FUNDAMENTAL_VALUATION_AUDIT",
        "name": "Fundamental Valuation & Quality Audit",
        "category": "FUNDAMENTAL",
        "status": "ACTIVE",
        "version": "v1.8.4",
        "description": "Audits trailing P/E multiples, Price-to-Book, ROCE, Return on Equity (ROE), Debt-to-Equity solvency, and quarterly revenue growth vs historical 5-year averages.",
        "input_schema": {"symbol": "str", "financials": "Dict"},
        "output_schema": {"valuation_grade": "str", "solvency_score": "float", "fair_value_est": "float"},
        "latency_ms": 25,
        "tools_used": ["YahooFinanceMarketDataProvider", "FundamentalsAnalystAgent"],
    },
    {
        "skill_id": "SKILL_SENTIMENT_DERIVATIVES_DECODER",
        "name": "Derivatives & Institutional Sentiment Decoder",
        "category": "DERIVATIVES",
        "status": "ACTIVE",
        "version": "v3.0.1",
        "description": "Analyzes NSE Option Chain Put-Call Ratio (PCR Open Interest), Max Pain strike gravitation, Implied Volatility (IV) skew, and daily FII/DII net institutional cash flows.",
        "input_schema": {"symbol": "str", "option_chain": "Dict"},
        "output_schema": {"pcr_oi": "float", "max_pain_strike": "float", "fii_flow_bias": "str"},
        "latency_ms": 18,
        "tools_used": ["DerivativesEngine", "FiiDiiTracker", "SentimentAnalystAgent"],
    },
    {
        "skill_id": "SKILL_MACRO_GEOPOLITICAL_SENTINEL",
        "name": "Macro & Geopolitical Risk Sentinel",
        "category": "MACRO",
        "status": "ACTIVE",
        "version": "v2.0.0",
        "description": "Monitors RBI Monetary Policy Committee (MPC) repo rate trajectory, US 10-year Treasury yields, Brent crude oil price shocks, and USD/INR exchange rate volatility.",
        "input_schema": {"market_regime": "str", "macro_indicators": "Dict"},
        "output_schema": {"macro_regime": "str", "tail_risk_level": "str", "rate_sensitivity": "float"},
        "latency_ms": 40,
        "tools_used": ["NewsMacroAnalystAgent", "MarketRegimeClassifier"],
    },
    {
        "skill_id": "SKILL_DIALECTICAL_BULL_BEAR_DEBATE",
        "name": "Dialectical Bull vs Bear Multi-Agent Arena",
        "category": "AGENT_DEBATE",
        "status": "ACTIVE",
        "version": "v2.4.0",
        "description": "Orchestrates multi-agent dialectical argumentation between Bullish Growth Researcher and Bearish Risk Researcher to eliminate confirmation bias and uncover hidden traps.",
        "input_schema": {"analysts_reports": "Dict", "symbol": "str"},
        "output_schema": {"bullish_catalysts": "List[str]", "bearish_risks": "List[str]", "debate_verdict": "str"},
        "latency_ms": 120,
        "tools_used": ["BullishResearcherAgent", "BearishResearcherAgent", "LLMClient"],
    },
    {
        "skill_id": "SKILL_KELLY_CRITERION_RISK_ARBITER",
        "name": "Kelly Criterion Risk Arbiter & 3-Way Committee",
        "category": "RISK_GOVERNANCE",
        "status": "ACTIVE",
        "version": "v3.2.0",
        "description": "Hosts 3-way risk debate (Aggressive Growth vs Conservative Preservation) and computes mathematical Half-Kelly position sizing dynamically scaled by India VIX regime multipliers.",
        "input_schema": {"trade_proposal": "Dict", "india_vix": "float", "win_probability": "float"},
        "output_schema": {"recommended_allocation_pct": "float", "half_kelly_fraction": "float", "stop_buffer_atr": "float"},
        "latency_ms": 35,
        "tools_used": ["NeutralRiskArbiter", "AggressiveRiskDebator", "ConservativeRiskDebator"],
    },
    {
        "skill_id": "SKILL_STRATEGY_GENETIC_MUTATION",
        "name": "Strategy DSL Genetic Mutation & Evolution",
        "category": "QUANT_EVOLUTION",
        "status": "ACTIVE",
        "version": "v1.4.0",
        "description": "Autonomously analyzes backtest failure modes (low win rate, high drawdown) and performs AST genetic mutation to generate immutable child strategy versions with full lineage tracking.",
        "input_schema": {"parent_strategy": "StrategyDefinition", "backtest_metrics": "Dict"},
        "output_schema": {"mutated_strategy": "StrategyDefinition", "mutations_applied": "List[str]", "lineage_id": "str"},
        "latency_ms": 15,
        "tools_used": ["StrategyEvolutionAgent", "StrategyDefinition", "BacktestEngine"],
    },
    {
        "skill_id": "SKILL_POST_TRADE_ALPHA_REFLECTION",
        "name": "Post-Trade Alpha Reflection & Memory Bank",
        "category": "SELF_LEARNING",
        "status": "ACTIVE",
        "version": "v2.0.0",
        "description": "Compares closed virtual trade P&L against benchmark NIFTY 50 alpha, synthesizes terse institutional lessons, and persists them in the permanent Decision Memory Bank for prompt injection.",
        "input_schema": {"trade_record": "Dict", "nifty_alpha_pct": "float"},
        "output_schema": {"lesson_learned": "str", "memory_id": "str", "persisted": "bool"},
        "latency_ms": 85,
        "tools_used": ["Reflector", "LLMClient", "SQLite/PostgreSQL"],
    },
    {
        "skill_id": "SKILL_TINYFISH_LIVE_WEB_RESEARCH",
        "name": "TinyFish Real-Time Web & Filing Scraping",
        "category": "WEB_INTELLIGENCE",
        "status": "ACTIVE",
        "version": "v1.2.0",
        "description": "Executes live web scraping via official TinyFish API on NSE/BSE corporate exchange announcements, earnings call transcripts, credit rating revisions, and management commentary.",
        "input_schema": {"query": "str", "limit": "int"},
        "output_schema": {"filings": "List[Dict]", "key_takeaways": "List[str]"},
        "latency_ms": 320,
        "tools_used": ["TinyFishClient", "ResearchAgent"],
    },
    {
        "skill_id": "SKILL_KOKORO_NEURAL_TTS_VOICE",
        "name": "Kokoro Neural TTS Audio Briefing Synthesizer",
        "category": "MULTIMODAL_VOICE",
        "status": "ACTIVE",
        "version": "v1.1.0",
        "description": "Synthesizes high-fidelity natural speech audio digests for morning Dalal Street market openings, strategy alert notifications, and trade execution updates in Indian English accent.",
        "input_schema": {"text": "str", "voice": "str"},
        "output_schema": {"audio_path": "str", "duration_sec": "float", "file_format": "str"},
        "latency_ms": 150,
        "tools_used": ["KokoroTTSEngine", "edge-tts"],
    },
    {
        "skill_id": "SKILL_TALKING_AVATAR_VIDEO_STUDIO",
        "name": "Talking Avatar Video Briefing Studio",
        "category": "MULTIMODAL_VIDEO",
        "status": "ACTIVE",
        "version": "v1.0.0",
        "description": "Generates animated presenter video briefings from uploaded portrait images and synchronized speech audio for daily Dalal Street executive reports.",
        "input_schema": {"image_path": "str", "audio_path": "str", "script_text": "str"},
        "output_schema": {"video_path": "str", "resolution": "str", "status": "str"},
        "latency_ms": 280,
        "tools_used": ["TalkingAvatarEngine"],
    },
    {
        "skill_id": "SKILL_TELEGRAM_WHATSAPP_DISPATCHER",
        "name": "Telegram & WhatsApp Regulatory Alert Dispatcher",
        "category": "CONNECTORS",
        "status": "ACTIVE",
        "version": "v2.0.0",
        "description": "Dispatches formatted trade entry alerts, stop-loss adjustments, portfolio drawdown warnings, and morning audio voice notes to authorized Telegram Channels and WhatsApp Cloud API.",
        "input_schema": {"channel": "str", "alert_payload": "Dict", "attachment_path": "Optional[str]"},
        "output_schema": {"message_id": "str", "delivery_status": "str", "timestamp": "str"},
        "latency_ms": 95,
        "tools_used": ["TelegramConnector", "WhatsAppConnector"],
    },
]
