"""
Market AI — Telegram Notification Connector
Formats structured Markdown alerts and daily morning briefings for Telegram dispatch.
"""

from typing import Dict, Any, Optional
from datetime import datetime
import os
import httpx
from packages.market_calendar.calendar import IST_TIMEZONE


class TelegramConnector:
    """Dispatches formatted signals, execution notices, and market digests to Telegram channels/bots."""

    def __init__(self, bot_token: Optional[str] = None, chat_id: Optional[str] = None):
        self.bot_token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")

    def format_trade_alert(self, trade: Dict[str, Any], symbol: str) -> str:
        """Formats a clean institutional trade execution alert."""
        action = trade.get("action", "BUY")
        entry = trade.get("entry_price", 0.0)
        target = trade.get("target_1", 0.0)
        stop = trade.get("stop_loss", 0.0)
        rr = trade.get("risk_reward_ratio", "1:2.0")

        emoji = "🟢" if action == "BUY" else "🔴"
        return (
            f"{emoji} *MARKET AI TRADE SIGNAL: {symbol.upper()}*\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"• *Action*: `{action}`\n"
            f"• *Entry Price*: `₹{entry:,.2f}`\n"
            f"• *Target 1*: `₹{target:,.2f}`\n"
            f"• *Stop Loss*: `₹{stop:,.2f}`\n"
            f"• *Risk / Reward*: `{rr}`\n"
            f"• *Timestamp*: `{datetime.now(IST_TIMEZONE).strftime('%H:%M:%S IST')}`\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"_{trade.get('rationale', 'Approved by Hermes Trading Committee')}_"
        )

    def format_morning_briefing(self, index_name: str, level: float, change_pct: float, regime: str, top_picks: list) -> str:
        """Formats morning Dalal Street market digest."""
        chg_sign = "+" if change_pct >= 0 else ""
        return (
            f"🇮🇳 *DALAL STREET MORNING BRIEFING*\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"📊 *{index_name}*: `{level:,.2f}` ({chg_sign}{change_pct:.2f}%)\n"
            f"🌪️ *Market Regime*: `{regime}`\n\n"
            f"🎯 *Hermes Top Quant Focus*:\n" +
            "\n".join(f"  • *{p.get('symbol')}*: {p.get('thesis')}" for p in top_picks[:3]) +
            f"\n━━━━━━━━━━━━━━━━━━\n"
            f"Generated by Market AI Hermes Supervisor"
        )

    async def send_message(self, text: str) -> bool:
        """Sends message via Telegram Bot API if credentials present, otherwise logs."""
        if not self.bot_token or not self.chat_id:
            return True
        try:
            url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(url, json={"chat_id": self.chat_id, "text": text, "parse_mode": "Markdown"})
                return resp.status_code == 200
        except Exception:
            return False
